trunk/BugTracker/BugTracker/ViewModels/BugDiscussionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BugTracker.Model;

namespace BugTracker.ViewModels
{
    public class BugDiscussionViewModel
    {
        public BugDiscussions Discussion { get; set; }
    }
}

trunk/BugTracker/BugTracker/ViewModels/BugViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BugTracker.Model;

namespace BugTracker.ViewModels
{
    public class BugViewModel
    {
        public Bugs Bug { get; set; }
    }
}

trunk/BugTracker/BugTracker/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BugTracker.Model;

namespace BugTracker.ViewModels
{
    public class ProjectViewModel
    {
        public Project Project { get; set; }
    }
}

trunk/BugTracker/BugTracker/ViewModels/UserProfilesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BugTracker.Model;

namespace BugTracker.ViewModels
{
    public class UserProfilesViewModel
    {
        public UserProfile Profile { get; set; }
    }
}

trunk/BugTracker/BugTracker/ViewModels/UsersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTracker.Model;

namespace BugTracker.ViewModels
{
    public class UsersViewModel
    {
        public Users Users { get; set; }
        public IEnumerable<SelectListItem> UserTypes { get; set; }
        public UsersViewModel() { }
        public UsersViewModel(Users User)
        {
            Users = User;
        }        
    }
}

trunk/BugTracker/BugTracker/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;


namespace BugTracker.Controllers
{
     [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public abstract class BaseController : Controller
    {             
    }
}

trunk/BugTracker/BugTracker/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTracker.ViewModels;
using BugTracker.Model;
using BugTracker.Domain.Handlers;

namespace BugTracker.Controllers
{
    public class UsersController : Controller
    {
        private UsersViewModel _ViewModel = new UsersViewModel();
        private UsersHandler _handler = new UsersHandler();

        public ActionResult Index()
        {
            var users = _handler.GetAllUsers().Select(m => new UsersViewModel(new Users()
            {
                Username=m.Username
            }));
            return View(users);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Create()
        {
            Initialize(ref _ViewModel);
            return View(_ViewModel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(FormCollection form, UsersViewModel _Model)
        {
            Initialize(ref _Model);
            //_Model.UserTypes.Where(m => m.Value.Equals(_Model.Users.UserTypeID)).SingleOrDefault(n => n.Selected = true);
            return View(_Model);
        }

        private void Initialize(ref UsersViewModel init)
        {
            //Bind UserTypes Dropdownlist
            init.UserTypes = _handler.GetUserTypes().Select(m => new SelectListItem()
            {
                Text = m.Value,
                Value = m.Key
            });
        }

        
        public JsonResult IsUsername_Available(string Username, string Email)
        {
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult IsEmail_Available(string Email, string Username)
        {
            return Json(false, JsonRequestBehavior.AllowGet);
        }

    }
}

trunk/BugTracker/BugTracker/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="title">
    Index
</div>

@ViewBag.Result

@using (Html.BeginForm("Index", "Default", FormMethod.Post))
{
    <p>
        <input type="text" name="username" id="username" />
        <input type="password" name="password" id="password" />
        <input type="submit" value="Signin" />
    </p>
}

trunk/BugTracker/BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @* Global Stylesheets *@
    <link href="@Url.Content("~/Content/themes/custom/jquery-ui-1.10.3.custom.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/sitestyles.css")" rel="stylesheet" type="text/css" />
    @RenderSection("styles", false)
    
    
    @* JavaScript Libraries *@
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>*@
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    

    @* User Scripts *@
    <script src="@Url.Content("~/Scripts/local-scripts/global.js")" type="text/javascript"></script>
    @RenderSection("scripts", false)
</head>
<body>
    <div id="wrapper">
        <div id="pgHeader">                
        <img id="zsllogo" alt="" src="@Url.Content("~/Content/images/zsl-logo.jpg")" />
        <span>Bug Tracker</span>        
        </div>
        <div id="pgContent">
            @RenderBody()
        </div>
       @* <div id="pgFooter">
            <p>&copy; Copywright 2013, Zylog Systems Limited.Best viewed in resolution 1000x800</p>
        </div>*@
    </div>
</body>
</html>

trunk/BugTracker/BugTracker/Views/Users/Create.cshtml
@model BugTracker.ViewModels.UsersViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script src="@Url.Content("~/Scripts/local-scripts/users-scripts.js")" type="text/javascript"></script>
}

@*@using (Html.BeginForm("Create", "Users", FormMethod.Post, new { id = "form1", @class = "small-forms" }))*@
@using (Ajax.BeginForm("Create",null,new AjaxOptions(){ UpdateTargetId="form1" }, new { id = "form1", @class = "small-forms" }))
{    
    <fieldset>
        <legend>User Registration</legend>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.Username)</div>
            <div class="col2">@Html.TextBoxFor(m => m.Users.Username, new { @class = "textbox" })</div>
            @Html.ValidationMessageFor(m => m.Users.Username)
        </div>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.Password)</div>
            <div class="col2">@Html.PasswordFor(m => m.Users.Password, new { @class = "textbox" })</div>
            @Html.ValidationMessageFor(m => m.Users.Password)
        </div>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.Email)</div>
            <div class="col2">@Html.TextBoxFor(m => m.Users.Email, new { @class = "textbox" })</div>
            @Html.ValidationMessageFor(m => m.Users.Email)
        </div>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.UserTypeID)</div>
            <div class="col2">
                @Html.DropDownListFor(m => m.Users.UserTypeID, new SelectList(Model.UserTypes, "Value", "Text"), new {@class="select" })
            </div>
        </div>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.IsZsl)</div>
            <div class="col2">
                YES: @Html.RadioButtonFor(m => m.Users.IsZsl, "True", new { title="ZSL User",@checked=true })
                NO: @Html.RadioButtonFor(m => m.Users.IsZsl, "False", new { title = "Other Domain User" })
            </div>
        </div>
        <div class="form-row">
            <div class="col1">@Html.LabelFor(m => m.Users.IsActive)</div>
            <div class="col2">
                YES: @Html.RadioButtonFor(m => m.Users.IsActive , "True", new { @checked=true })
                NO: @Html.RadioButtonFor(m => m.Users.IsActive, "False")
            </div>
        </div>
        <div class="form-buttons">
            <p>
                <button type="submit" class="save-button">
                    Save</button>
            </p>
        </div>
    </fieldset> 
}

trunk/BugTracker/BugTracker/Views/Users/Index.cshtml
@model IEnumerable<BugTracker.ViewModels.UsersViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.Label(item.Users.Username)</td>
    </tr>
    @*<tr>
        <td>@Html.Display(item.User.Password)</td>
    </tr>
    <tr>
        <td>@Html.Display(item.User.ModifiedDate.ToString())</td>
    </tr>
    <tr>
        <td>@Html.Display(item.User.IsZsl.ToString())</td>
    </tr>
    <tr>
        <td>@Html.Display(item.User.IsActive.ToString())</td>
    </tr>
    <tr>
        <td>@Html.Display(item.User.Email.ToString())</td>
    </tr>*@
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>